version: '3.9'

services:
  backend:
    build:
      context: "."
      args:
        - ENV=prod
    restart: always
    networks:
      - app-network
    ports:
      - "3000:3000"

  nginx-frontend:
    build:
      context: ./frontend/
      args:
        - ENV=prod
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network: