name: Production Enviroment CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: aws-ec2

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose down
        run: docker-compose -f docker-compose-prod.yml down

      - name: Docker Compose build and up
        run: docker-compose -f docker-compose-prod.yml up --build -d