name: Test Enviroment CI

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: aws-ec2-test

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose down
        run: docker-compose -f docker-compose-test.yml down

      - name: Docker Compose build and up
        run: docker-compose -f docker-compose-test.yml up --build -d
       
      - name: API-consumer-driven-contract-test
        working-directory: 'frontend'
        run: docker build -f Dockerfile-contractTests -t dredd .

      - name: UI Acceptance tests
        working-directory: 'frontend'
        run: docker build -f Dockerfile-e2e -t cypress .