name: Cypress Test
on:
  push:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      - name: Run cypress tests
        working-directory: './frontend'
        run: npm run test:e2e
        continue-on-error: false
